push-protocol/push-sdk

- packages/restapi/src/lib/index.ts
> feat(restapi): stable version

- packages/uiweb/README.md
> feat(uiweb): make it 0.1.0

- packages/socket/README.md
> feat(socket): make it stable

- packages/reactnative/README.md
> feat(reactnative): stable 0.1.0

- packages/uiembed/README.md
> feat(uiembed): make it 0.1.0

- packages/restapi/README.md
> docs(restapi): changed the goerli comm address in docs

- packages/uiembed/README.md
> docs(uiembed): update docs

- README.md
> docs(all): add rn docs link

- packages/demoreact/src/app/ChatTest/CreateGroupTest.tsx
- packages/demoreact/src/app/ChatTest/UpdateGroupTest.tsx
- packages/restapi/src/lib/chat/createGroup.ts
- packages/restapi/src/lib/chat/helpers/payloadHelper.ts
- packages/restapi/src/lib/chat/helpers/validator.ts
- packages/restapi/src/lib/chat/updateGroup.ts
- packages/restapi/src/lib/types/index.ts
Group Image parameter in the update group API to be consistent
> fix(component): group chat SDK changes and improvements

- packages/demoreact/src/app/ChatTest/ApproveRequestTest.tsx
- packages/restapi/src/lib/chat/approveRequest.ts
- packages/restapi/src/lib/chat/helpers/payloadHelper.ts
- packages/restapi/src/lib/chat/send.ts
- packages/restapi/src/lib/chat/start.ts
> fix(component): implemented signature validation for create and update indent

- packages/demoreact/src/app/ChatTest/SendMessageTest.tsx
- packages/restapi/src/lib/types/index.ts
Enable SDK to send MeidaURL type messages
> feat: MediaURL type message support

- packages/restapi/src/lib/chat/approveRequest.ts
- packages/restapi/src/lib/chat/createGroup.ts
- packages/restapi/src/lib/chat/helpers/service.ts
- packages/restapi/src/lib/chat/historicalMessages.ts
- packages/restapi/src/lib/chat/send.ts
- packages/restapi/src/lib/chat/start.ts
- packages/restapi/src/lib/chat/updateGroup.ts
- packages/restapi/src/lib/chat/updateUser.ts
- packages/restapi/src/lib/types/index.ts
- packages/restapi/src/lib/user/createUser.ts
- packages/restapi/src/lib/user/upgradeUser.ts
Change return types from `Promise <any>` to `Promise <TYPE_OF_DATA_RETURNED>`
Fix conversationHash return type from `Promise<string>` to `Promise<{threadhash : string}>`
> Added types for chat fn

- packages/restapi/package.json
Removed  ts-node, chai, typescript and mocha-typescript packages from dependencies and added those in devDependencies.
> Removed extra dependencies and added those in devDependencies

- packages/demoreact/src/app/ChatTest/GetChats.tsx
- packages/demoreact/src/app/ChatTest/GetRequests.tsx
- packages/restapi/src/lib/chat/chats.ts
- packages/restapi/src/lib/chat/helpers/inbox.ts
- packages/restapi/src/lib/chat/requests.ts
- packages/restapi/src/lib/types/index.ts
> Add: pagination and deprecation tag for chats & req

- packages/examples/sdk-backend-node/src/main.ts
- packages/restapi/src/lib/channels/_getSubscribers.ts
- packages/restapi/src/lib/channels/getChannel.ts
- packages/restapi/src/lib/channels/getDelegates.ts
- packages/restapi/src/lib/channels/getSubscribers.ts
- packages/restapi/src/lib/channels/subscribe.ts
- packages/restapi/src/lib/channels/unsubscribe.ts
- packages/restapi/src/lib/helpers/address.ts
- packages/restapi/src/lib/payloads/helpers.ts
- packages/restapi/src/lib/payloads/sendNotifications.ts
- packages/restapi/src/lib/user/getDelegations.ts
- packages/restapi/src/lib/user/getFeeds.ts
- packages/restapi/src/lib/user/getSubscriptions.ts
Enables Video Call Notification from NFT-Based Accounts.
This PR already live and tested on alpha
> fix:NFT videocall

- packages/demoreact/src/app/SpaceUITest/index.tsx
- packages/uiweb/src/lib/components/space/SpaceBanner/SpaceBanner.tsx
- packages/uiweb/src/lib/components/space/SpaceWidget/SpaceWidget.tsx
- packages/uiweb/src/lib/components/space/theme/index.ts
Updated the theme acc. to figma design: [Figma URL](https://www.figma.com/file/PzAmXUMOmwS2ljxufwv44m/PUSH-Prototypes?node-id=14376%3A46137&mode=dev)
> refactor: updated theme object along with light and dark theme

- packages/uiweb/src/lib/components/space/SpaceCreationWidget/SCWInviteModal/SCWInviteModal.tsx
- packages/uiweb/src/lib/components/space/SpaceWidget/SpaceWidget.tsx
- packages/uiweb/src/lib/components/space/SpaceWidget/SpacesInfo.tsx
- packages/uiweb/src/lib/components/space/SpaceWidget/WidgetContent.tsx
- packages/uiweb/src/lib/components/space/SpaceWidget/WidgetHeader.tsx
- packages/uiweb/src/lib/components/space/reusables/Accordion.tsx
- packages/uiweb/src/lib/components/space/reusables/Modal.tsx
- replaced hardcoded styles with context theme
- added smoother animations on collapsoble components
- added profile cards to invite modal
> rft: Spaces UI Components Refactor

- packages/uiweb/src/lib/components/chatAndNotification/ChatAndNotification.tsx
- packages/uiweb/src/lib/components/chatAndNotification/MinimisedModalHeader.tsx
- packages/uiweb/src/lib/components/chatAndNotification/modal/messageBox/MessageBox.tsx
- packages/uiweb/src/lib/components/chatAndNotification/modal/sidebar/Sidebar.tsx
- packages/uiweb/src/lib/components/chatAndNotification/modal/sidebar/chatSidebar/ChatSnap.tsx
- packages/uiweb/src/lib/helpers/chat/search.ts
- Existing user can be searched through search
- New wallet will be displayed as a separate chat.
> Fixed issue for search in chat

- packages/demoreact/src/app/SpaceUITest/SpaceBanner.tsx
- packages/uiweb/src/lib/components/space/SpaceBanner/SpaceBanner.tsx
> refactor: added a clickHandler in spaceBanner component for extra flexibility

- packages/uiweb/src/lib/components/chatAndNotification/ChatAndNotification.tsx
- packages/uiweb/src/lib/components/chatAndNotification/modal/messageBox/MessageBox.tsx
- packages/uiweb/src/lib/components/chatAndNotification/modal/sidebar/chatSidebar/ChatsFeedList.tsx
Scrollbar issue is fixed in the chat Feeds list and the message box. Also fixed in the notifications
> fix: scrollbar issue fixed

- packages/uiweb/src/lib/components/chatAndNotification/MinimisedModalHeader.tsx
- packages/uiweb/src/lib/components/chatAndNotification/modal/messageBox/MessageBox.tsx
- packages/uiweb/src/lib/components/chatAndNotification/modal/messageBox/typebar/Typebar.tsx
- packages/uiweb/src/lib/components/chatAndNotification/modal/sidebar/Sidebar.tsx
- packages/uiweb/src/lib/components/chatAndNotification/modal/sidebar/chatSidebar/ChatSnap.tsx
- packages/uiweb/src/lib/helpers/chat/time.ts
- Accept Button is fixed according to the design.
- Time format is changed to local.
- Typebar UI is fixed and now after 4 rows only the scrollbar will be displayed.
> fix: chat UI fixes

- packages/uiweb/src/lib/components/space/SpaceCreationWidget/SCWInviteModal/SCWInviteModal.tsx
- packages/uiweb/src/lib/components/space/SpaceCreationWidget/SpaceCreationWidget.tsx
- packages/uiweb/src/lib/components/space/helpers/blockies.ts
added blockies for non push users
increased scheduling time of instant space to Date.now() + 2mins
> feat: add blockies

- packages/uiweb/src/lib/components/space/SpaceCreationWidget/SCWInviteModal/SCWInviteModal.tsx
- packages/uiweb/src/lib/components/space/SpaceWidget/SpacesInfo.tsx
- packages/uiweb/src/lib/components/space/SpaceWidget/WidgetHeader.tsx
- packages/uiweb/src/lib/components/space/reusables/Accordion.tsx
refactored info modal - added spaceData
added custom search function for invite users modal
> feat: info modal rft

- packages/uiweb/src/lib/components/chat/ChatProfile/ChatProfile.tsx
earlier every group used to have that token gated Icon but using this only those which are token gated will show that icon
> fix: added condition while showing tokengatedIcon

- packages/examples/sdk-backend-node/.env.sample
- packages/examples/sdk-backend-node/video/index.ts
> fix(env and index): fixes typo RECIPEINT to RECIPIENT

- .github/ISSUE_TEMPLATE/BUG_REPORT.yml
- .github/ISSUE_TEMPLATE/DOCUMENTATION_README_ISSUE.yml
- .github/ISSUE_TEMPLATE/IMPROVEMENT_PROPOSAL.yml
- .github/ISSUE_TEMPLATE/OTHER.yml
- .github/ISSUE_TEMPLATE/QUESTION_SUPPORT.yml
Functionalites :
- Bug report 
- Documentation enhancement
- Improvement proposal
- Other
- Questions or report request
> Added a ISSUE template

- packages/uiweb/src/lib/components/parsetext/defaultPatterns.ts
added span tag for text with color
> Tag default pattern

- CONTRIBUTING.md
> docs(contributing.md): fixes typo in contributing.md

- README.md
> docs: changed link of contributing

- packages/examples/sdk-backend-node/notification/notification.ts
- packages/examples/sdk-backend-node/package.json
> chore: bump sdk version, shift to new subscribe fn

- packages/restapi/src/lib/pushstream/socketClient.ts
> fix: socket url fix

- packages/restapi/src/lib/chat/helpers/crypto.ts
- packages/restapi/src/lib/chat/helpers/inbox.ts
Closes #1011
1. Fix mismatch in pgpHelper method invocations 
2. Add default param to decryptConversation function
> pgpHelper fixes

- packages/uiweb/src/lib/components/chat/ChatProfile/ChatProfile.tsx
- packages/uiweb/src/lib/components/chat/constants/index.ts
- packages/uiweb/src/lib/context/chatContext.ts
- packages/uiweb/src/lib/dataProviders/ChatDataProvider.tsx
- packages/uiweb/src/lib/helpers/chat/search.ts
- packages/uiweb/src/lib/hooks/chat/index.ts
- packages/uiweb/src/lib/hooks/chat/useChatProfile.ts
- packages/uiweb/src/lib/hooks/chat/useInitializePushUser.ts
- packages/uiweb/src/lib/hooks/chat/usePushChatStream.ts
- packages/uiweb/src/lib/hooks/chat/usePushUserInfoUtilities.ts
> fix: added pushUser and stream

- packages/uiweb/src/lib/components/chat/ChatPreviewList/ChatPreviewList.tsx
- packages/uiweb/src/lib/context/chatContext.ts
- packages/uiweb/src/lib/dataProviders/ChatDataProvider.tsx
- packages/uiweb/src/lib/helpers/chat/chat.ts
- packages/uiweb/src/lib/hooks/chat/index.ts
- packages/uiweb/src/lib/hooks/chat/useChatProfile.ts
- packages/uiweb/src/lib/hooks/chat/useFetchMessageUtilities.ts
- packages/uiweb/src/lib/hooks/chat/useGetGroupByIDnew.ts
- packages/uiweb/src/lib/hooks/chat/useInitializeUser.ts
- packages/uiweb/src/lib/hooks/chat/usePushChatStream.ts
- packages/uiweb/src/lib/hooks/chat/useUserInfoUtilities.ts
- packages/uiweb/src/lib/types/index.ts
> fix: changed pushUser to user

- packages/examples/sdk-frontend-react/src/app/Video/index.tsx
- packages/restapi/src/lib/constantsV2.ts
- packages/restapi/src/lib/index.ts
- packages/restapi/src/lib/pushapi/video.ts
- packages/restapi/src/lib/types/index.ts
- packages/restapi/src/lib/video/VideoV2.ts
Pls reference the attached issue for details regarding the changes.
> Minor fixes and improvements in video v2

- packages/examples/sdk-frontend/helpers/getCAIPAddress.ts
- packages/examples/sdk-frontend/package.json
- packages/examples/sdk-frontend/pages/_app.tsx
- packages/examples/sdk-frontend/pages/video-v2.tsx
- packages/examples/sdk-frontend/pages/video.tsx
> 1050 update video example implementation nextjs

- packages/restapi/src/lib/pushapi/PushAPI.ts
- packages/restapi/tests/lib/chat/chat.test.ts
- packages/restapi/tests/lib/encryption/encryption.test.ts
> fix: public key in read mode

- packages/uiweb/src/lib/components/chat/ChatPreviewList/ChatPreviewList.tsx
- packages/uiweb/src/lib/components/chat/helpers/helper.ts
> Review bugs

- packages/restapi/src/lib/helpers/crypto.ts
- packages/restapi/tests/lib/encryption/encryption.test.ts
> fix: v2 user creation / upgrades / downgrades

- packages/uiweb/src/lib/components/chat/ChatPreview/ChatPreview.tsx
- packages/uiweb/src/lib/components/chat/ChatPreviewList/ChatPreviewList.tsx
media emoji
stream connection fix, now the new inbox shows in the chats
> fix: media emoji added

- packages/restapi/README.md
> docs(restapi): update restapi readme

- packages/restapi/src/lib/chat/helpers/crypto.ts
- packages/restapi/tests/lib/chat/privateGroup.test.ts
> fix: added caching to grp message decryption

- packages/restapi/tests/lib/chat/privateGroup.test.ts
> test: fix private grps testcases

- packages/restapi/src/lib/progressHook.ts
> fix: progressHook info message changes

- packages/examples/sdk-frontend-react/src/app/ChatUITest/ChatViewComponent.tsx
- packages/uiweb/src/lib/components/chat/ChatViewList/ChatViewList.tsx
- packages/uiweb/src/lib/components/chat/constants/index.ts
- packages/uiweb/src/lib/components/chat/helpers/helper.ts
- packages/uiweb/src/lib/types/index.ts
> fix: added nonce for chat list api call

- packages/examples/sdk-frontend-react/src/app/ChatUITest/ChatViewComponent.tsx
- packages/uiweb/src/lib/components/chat/ChatViewList/ChatViewList.tsx
- packages/uiweb/src/lib/components/chat/constants/index.ts
- packages/uiweb/src/lib/components/chat/helpers/helper.ts
- packages/uiweb/src/lib/types/index.ts
Reverts ethereum-push-notification-service/push-sdk#1013
> Revert "fix: added nonce for chat list api call"

- packages/examples/sdk-frontend-react/src/app/ListChannelsTest.tsx
- packages/examples/sdk-frontend-react/src/app/app.tsx
- packages/restapi/src/lib/channels/getChannels.ts
- packages/restapi/src/lib/channels/index.ts
- packages/restapi/src/lib/constantsV2.ts
- packages/restapi/src/lib/pushNotification/PushNotificationTypes.ts
- packages/restapi/src/lib/pushNotification/channel.ts
- packages/restapi/src/lib/pushapi/pushAPITypes.ts
> Added channel.list API

- packages/restapi/src/lib/channels/getChannelNotifications.ts
- packages/restapi/src/lib/constantsV2.ts
- packages/restapi/src/lib/pushNotification/PushNotificationTypes.ts
- packages/restapi/src/lib/pushNotification/channel.ts
- packages/restapi/tests/lib/notification/channel.test.ts
> fix: channel.notifications response

- packages/uiweb/src/lib/components/widget/subscriptionManager/SettingsComponents.tsx
> fix: added settings name

- packages/uiweb/src/lib/hooks/chat/useChatProfile.ts
> User info giving undefined issue fix

- packages/examples/sdk-frontend-react/src/app/ChatUITest/ChatProfile.tsx
Reverts push-protocol/push-sdk#1200
> Revert "Alpha deployment"

- packages/restapi/tests/lib/chat/chat.test.ts
- packages/restapi/tests/lib/notification/delegate.test.ts
- packages/restapi/tests/lib/notification/notification.test.ts
- packages/restapi/tests/lib/progressHook/progressHookData.ts
- packages/restapi/tests/lib/space/space.test.ts
- packages/restapi/tests/lib/stream/space.test.ts
- packages/restapi/tests/lib/video/sendVideoNotification.test.ts
> test: fix testcases

- packages/reactnative/package.json
> Fixes RN sdk deployment and patch not running

- packages/uiweb/src/lib/components/notification/index.tsx
- packages/uiweb/src/lib/hooks/chat/useGroupMemberUtilities.ts
> Notification icon fix

- package.json
- packages/uiweb/package.json
- packages/uiweb/src/lib/components/chat/ChatProfile/ChatProfile.tsx
- packages/uiweb/src/lib/components/chat/ChatView/ChatViewComponent.tsx
- packages/uiweb/src/lib/components/chat/ChatViewBubble/ChatViewBubble.tsx
- packages/uiweb/src/lib/components/chat/ChatViewBubble/cards/message/MessageCard.tsx
- packages/uiweb/src/lib/components/chat/ChatViewList/ChatViewList.tsx
- packages/uiweb/src/lib/components/chat/theme/index.ts
- packages/uiweb/src/lib/dataProviders/ChatDataProvider.tsx
- packages/uiweb/yarn.lock
> Sdk update chat info

- CONTRIBUTING.md
- README.md
- packages/examples/boilerplate/index.js
- packages/examples/sdk-backend-node/Readme.md
- packages/examples/sdk-backend-node/notification/notification.lowlevel.ts
- packages/examples/sdk-frontend-react/Readme.md
- packages/examples/sdk-frontend-react/src/app/ChatUITest/ChatProfile.tsx
- packages/reactnative/README.md
- packages/reactnative/push-react-native-sdk.podspec
- packages/restapi/CHANGELOG.md
- packages/socket/CHANGELOG.md
- packages/uiembed/CHANGELOG.md
- packages/uiweb/CHANGELOG.md
- packages/uiweb/README.md
- packages/uiweb/dist/packages/restapi/packages/restapi/CHANGELOG.md
- packages/uiweb/dist/packages/socket/packages/socket/CHANGELOG.md
- packages/uiweb/package.json
- packages/uiweb/src/lib/components/chat/ChatProfile/ChatProfile.tsx
- packages/uiweb/src/lib/components/chat/ChatViewList/ActionRequestBubble.tsx
- packages/uiweb/src/lib/components/chat/ChatViewList/ChatViewList.tsx
- packages/uiweb/src/lib/components/chat/MessageInput/MessageInput.tsx
- packages/uiweb/src/lib/components/chat/types/index.ts
- packages/uiweb/yarn.lock
> Uiweb chat info fixes

- packages/uiweb/.babelrc
- packages/uiweb/package.json
- packages/uiweb/yarn.lock
Closes #1288
Babel plugin to resolve relative imports
> added relative imports for better management

- packages/restapi/src/lib/progressHook.ts
> fix: fixed typos

- packages/reactnative/package.json
This is necessary to fix issues related to auto linking and archiving on iOS
Related to the following
https://github.com/jerson/react-native-fast-openpgp/issues/106
Fixed in this version
https://www.npmjs.com/package/react-native-fast-openpgp/v/2.7.3
> Updating react-native-fast-openpgp

- packages/reactnative/package.json
Closes #1211 
A description field added to the package.json to prevent IOS build errors.
> fix: Updated package.json to fix podspec build issue (#1211)
