push-protocol/push-sdk

packages/restapi/src/lib/utils/parseAPI.ts
fix #139
- Modifies title in return object of `parseApiResponse` to asub, or empty string if asub is falsy.
=> Fix parse api response of notifications

packages/restapi/src/lib/video/Video.ts
- Destroy the peer instance in the handler functions of END_CALL
- Minor: Remove unnecessary logs
=> fix: destroy peer instance in disconnect

packages/uiweb/src/lib/components/space/SpaceBanner/SpaceBanner.tsx, packages/uiweb/src/lib/components/space/SpaceInvites/SpaceInvites.tsx
the invite modal called the joinSpace API, which was again being called in the LiveWidget component, which led to the API being called twice.
The fix was to remove the API call from the SpaceInvite modal as the invite modal opened the LiveWidget, which by design called the joinSpace API through useEffect.
This has been tested for both Speaker as well as Listener ✅
=> fix: multi join issue in invites modal

packages/examples/sdk-frontend-react/src/app/ChatSupportTest.tsx, packages/uiweb/src/lib/components/supportChat/AddressInfo.tsx, packages/uiweb/src/lib/components/supportChat/Chat.tsx, packages/uiweb/src/lib/components/supportChat/ChatInput.tsx, packages/uiweb/src/lib/components/supportChat/Chats.tsx, packages/uiweb/src/lib/components/supportChat/Modal.tsx, packages/uiweb/src/lib/helpers/chat/chat.ts, packages/uiweb/src/lib/helpers/timestamp.ts, packages/uiweb/src/lib/hooks/useSDKSocket.ts, packages/uiweb/src/lib/types/index.ts, packages/uiweb/yarn.lock
Things changed:
- Shifted to new class based components for support chat
=> Support chat class based

.husky/pre-commit, packages/examples/sdk-frontend/package.json, packages/restapi/README.md, packages/restapi/src/lib/types/index.ts, packages/restapi/src/lib/video/Video.ts
- Update video docs
- Minor: Fix param type of disconnect method
=> docs(video): update push video docs

packages/restapi/src/lib/pushapi/chat.ts, packages/restapi/src/lib/pushapi/pushAPITypes.ts
=> fix case for member Status string

packages/examples/sdk-frontend-react/src/app/ChatUITest/ChatProfile.tsx, packages/examples/sdk-frontend-react/src/app/ChatUITest/ChatViewComponent.tsx, packages/uiweb/src/lib/components/chat/ChatProfile/AddWalletContent.tsx, packages/uiweb/src/lib/components/chat/ChatProfile/ChatProfile.tsx, packages/uiweb/src/lib/components/chat/ChatViewComponent/ChatViewComponent.tsx, packages/uiweb/src/lib/components/chat/CreateGroup/AddWallets.tsx, packages/uiweb/src/lib/components/chat/exportedTypes.ts
added an option in chat profile to pass a component so that features like video or other customizations can be implemented easily
=> 948 passvideo chatprofile

packages/restapi/README.md, packages/restapi/package.json, packages/restapi/src/lib/channels/subscribe.ts, packages/restapi/src/lib/channels/subscribeV2.ts, packages/restapi/src/lib/channels/unsubscribe.ts, packages/restapi/src/lib/channels/unsubscribeV2.ts, packages/restapi/src/lib/chat/helpers/crypto.ts, packages/restapi/src/lib/chat/helpers/signature.ts, packages/restapi/src/lib/chat/helpers/wallet.ts, packages/restapi/src/lib/helpers/address.ts, packages/restapi/src/lib/helpers/crypto.ts, packages/restapi/src/lib/helpers/signer.ts, packages/restapi/src/lib/payloads/helpers.ts, packages/restapi/src/lib/pushNotification/channel.ts, packages/restapi/src/lib/pushNotification/delegate.ts, packages/restapi/src/lib/pushNotification/pushNotificationBase.ts, packages/restapi/src/lib/types/index.ts, packages/restapi/tests/lib/benchmark/privateGroup.test.ts, packages/restapi/tests/lib/benchmark/publicGroup.test.ts, packages/restapi/tests/lib/notification/alias.test.ts, packages/restapi/tests/lib/notification/base.test.ts, packages/restapi/tests/lib/notification/channel.test.ts, packages/restapi/tests/lib/notification/delegate.test.ts, packages/restapi/tests/lib/notification/notification.test.ts, packages/restapi/tests/lib/stream/initialize.test.ts, packages/restapi/yarn.lock
=> Ethers V6 Support

package.json, packages/examples/sdk-frontend-react/project.json, packages/examples/sdk-frontend-react/src/webpack.config.js, yarn.lock
#978 
Install the latest dependencies before testing this PR
=> chore: fix polyfill issues

packages/restapi/src/lib/chat/helpers/crypto.ts
=> fix: message parsing by sdk

packages/examples/sdk-frontend-react/src/app/ChatUITest/ChatProfile.tsx, packages/uiweb/src/lib/components/chat/ChatPreview/ChatPreview.tsx, packages/uiweb/src/lib/components/chat/ChatPreviewList/ChatPreviewList.tsx, packages/uiweb/src/lib/components/chat/ChatProfile/ChatProfile.tsx, packages/uiweb/src/lib/helpers/address.ts, packages/uiweb/src/lib/helpers/chat/search.ts, packages/uiweb/src/lib/helpers/chat/user.ts, packages/uiweb/src/lib/hooks/chat/usePushChatStream.ts, packages/uiweb/src/lib/hooks/useResolveWeb3Name.ts
=> fix: fixed preview bugs

packages/restapi/src/lib/chat/helpers/inbox.ts
=> fix: optimize chat.list

packages/restapi/src/lib/pushapi/chat.ts, packages/restapi/src/lib/pushapi/pushAPITypes.ts, packages/restapi/tests/lib/chat/chat.group.test.ts, packages/restapi/tests/lib/chat/chat.test.ts
=> fix: allow groupImage and groupDesc to be updated to null

packages/restapi/README.md, packages/restapi/package.json, packages/restapi/src/lib/chat/helpers/signature.ts, packages/restapi/src/lib/helpers/signer.ts, packages/restapi/src/lib/pushNotification/pushNotificationBase.ts, packages/restapi/src/lib/types/index.ts, packages/restapi/yarn.lock
=> Mark ethers optional

packages/restapi/src/lib/pushapi/PushAPI.ts
#1091
Turn autoUpgrade True in low level SDK fns
=> fix(autoupgrade): turn autoUpgrade True in low level SDK fns

packages/uiweb/src/lib/components/chat/reusables/Modal.tsx
Reverts ethereum-push-notification-service/push-sdk#1152
=> Revert "fix: z-index modal"

packages/restapi/src/lib/helpers/crypto.ts, packages/restapi/src/lib/progressHook.ts, packages/restapi/src/lib/user/createUser.ts
=> fix: mark push-create-02 as deprecated

packages/restapi/src/lib/pushstream/DataModifier.ts, packages/restapi/src/lib/pushstream/PushStream.ts, packages/restapi/src/lib/pushstream/pushStreamTypes.ts, packages/restapi/tests/lib/stream/group.events.test.ts, packages/restapi/tests/lib/stream/space.test.ts
=> Fix role change stream event

packages/restapi/package.json, packages/restapi/tests/.env.sample, packages/restapi/tests/loaders/envVerifier.ts, packages/restapi/tests/root.ts
#1140 
Create `.env.sample` for Restapi test cases
=> Create .env.sample for Restapi test cases

packages/examples/sdk-frontend-react/src/app/ChatSupportTest.tsx, packages/uiweb/src/lib/components/chat/ChatProfile/ChatProfile.tsx, packages/uiweb/src/lib/components/chat/reusables/Modal.tsx, packages/uiweb/src/lib/components/supportChat/Chats.tsx
=> fix: horizontal scroll

packages/examples/sdk-frontend-react/src/app/ChatUITest/ChatPreviewList.tsx, packages/examples/sdk-frontend-react/src/app/ChatUITest/ChatProfile.tsx, packages/uiweb/src/lib/components/chat/ChatPreviewList/ChatPreviewList.tsx, packages/uiweb/src/lib/components/chat/ChatProfile/GroupInfoModal.tsx, packages/uiweb/src/lib/components/chat/ChatProfile/PendingMembers.tsx, packages/uiweb/src/lib/components/chat/UserProfile/UserProfile.tsx, packages/uiweb/src/lib/components/chat/reusables/AddWallets.tsx, packages/uiweb/src/lib/hooks/chat/useCreateGatedGroup.ts, packages/uiweb/src/lib/hooks/chat/usePushChatStream.ts
Fixed scrollbar in groupInfo
Whenever group is created it wasnt showing in chatPreviewList, fixed it.
Group creation without adding members, fixed the button disabled colour too
=> Group fixes

packages/restapi/src/lib/channels/subscribe.ts, packages/restapi/src/lib/channels/subscribeV2.ts, packages/restapi/tests/lib/channel/subscribeV2.test.ts
=> Add Referrer feild in subscriber

packages/uiweb/package-lock.json, packages/uiweb/package.json, packages/uiweb/src/lib/hooks/chat/useGroupMemberUtilities.ts
=> Alpha deployment

packages/uiweb/package.json, packages/uiweb/src/lib/components/chat/ChatViewBubble/ChatViewBubble.tsx, packages/uiweb/src/lib/components/chat/ChatViewList/ChatViewList.tsx, packages/uiweb/src/lib/components/chat/CreateGroup/AddCriteria.tsx, packages/uiweb/src/lib/components/chat/MessageInput/MessageInput.tsx, packages/uiweb/src/lib/components/chat/UserProfile/UserProfile.tsx
=> fix: fixed placement of chat

packages/examples/sdk-frontend-react/src/app/ChatUITest/ChatViewComponent.tsx, packages/uiweb/src/lib/components/chat/ChatViewList/ChatViewList.tsx
=> fix: fixed group issue

packages/restapi/src/lib/chat/getChatInfo.ts, packages/uiweb/dist/packages/restapi/packages/restapi/CHANGELOG.md, packages/uiweb/dist/packages/socket/packages/socket/CHANGELOG.md, packages/uiweb/package.json, packages/uiweb/src/lib/components/chat/ChatViewList/ChatViewList.tsx, packages/uiweb/src/lib/components/chat/ChatViewList/MessageEncryption.tsx, packages/uiweb/src/lib/components/chat/MessageInput/MessageInput.tsx, packages/uiweb/src/lib/components/chat/types/index.ts, packages/uiweb/yarn.lock
=> partial fix for chat info

packages/restapi/src/lib/pushNotification/notification.ts, packages/restapi/tests/lib/notification/notification.test.ts
=> fix: fixed issue with pcaip and no caip in optin and optout

packages/uiweb/src/lib/components/chat/ChatProfile/ChatProfile.tsx, packages/uiweb/src/lib/components/chat/ChatView/ChatViewComponent.tsx, packages/uiweb/src/lib/components/chat/ChatViewBubble/cards/message/FrameRenderer.tsx, packages/uiweb/src/lib/components/chat/ChatViewBubble/cards/message/MessageCard.tsx, packages/uiweb/src/lib/components/chat/MessageInput/MessageInput.tsx, packages/uiweb/src/lib/components/chat/reusables/ProfileContainer.tsx, packages/uiweb/src/lib/components/reusables/sharedStyling.tsx
Closes #1286 - Current responsiveness for Chat kinda breaks when viewed on mobile devices 400px or less. The PR addresses this.
Previous Implementation:
=> Fixed ChatUI Components responsiveness

packages/uiweb/src/lib/components/chat/ChatPreview/ChatPreview.tsx, packages/uiweb/src/lib/components/chat/ChatViewList/ChatViewList.tsx, packages/uiweb/src/lib/components/chat/ChatViewList/MessageEncryption.tsx, packages/uiweb/src/lib/components/chat/reusables/ProfileContainer.tsx, packages/uiweb/src/lib/components/chat/theme/index.ts, packages/uiweb/src/lib/components/reusables/sharedStyling.tsx
=> 🐛 [BUG] - <Skeleton loading in dark mode appears like light mode in chat>

packages/examples/sdk-frontend-react/src/app/ChatUITest/ChatPreview.tsx, packages/examples/sdk-frontend-react/src/app/constants.ts, packages/uiweb/src/lib/components/chat/ChatPreview/ChatPreview.tsx, packages/uiweb/src/lib/components/chat/ChatViewList/ChatViewList.tsx, packages/uiweb/src/lib/config/constants.ts
=> 🐛 [BUG] - Chat  badge getting updated for active/opened conversation>

packages/uiweb/src/lib/components/chat/ChatProfile/PendingMembers.tsx
When copying pending wallet address in the group info, only half of the wallet address was getting copied
#1297 
Closes: #1297 
0x9D964e3F0336acAB0AD2bA496a2Cb0cC5079F493 -> full wallet address gets copied
=> fix: pending wallet address copy issue fixed

packages/uiweb/src/lib/components/chat/ChatProfile/ChatProfileInfoModal.tsx, packages/uiweb/src/lib/components/chat/ChatProfile/PendingMembers.tsx
Tooltip was not properly aigned in the group Info in UIWeb
#1299 
Closes: #1299
=> fix: tooltip was not properly aligned

packages/uiweb/src/lib/components/chat/helpers/tokenGatedGroup.ts
=> fix: updated guild validation url

packages/restapi/tests/lib/notification/tags.test.ts, packages/restapi/tests/root.ts
=> chore: fix tc running

packages/restapi/src/lib/channels/getChannels.ts, packages/restapi/src/lib/channels/search.ts, packages/restapi/src/lib/pushNotification/PushNotificationTypes.ts, packages/restapi/src/lib/pushNotification/channel.ts, packages/restapi/tests/lib/channel/getChannels.test.ts, packages/restapi/tests/lib/channel/search.test.ts
=> fix: added tag parameter for filter in list

packages/restapi/src/lib/channels/search.ts, packages/restapi/tests/lib/channel/getChannels.test.ts, packages/restapi/tests/lib/channel/search.test.ts
=> fix: search response

packages/uiweb/src/lib/components/chat/ChatViewBubbleCore/cards/message/PreviewRenderer.tsx, packages/uiweb/src/lib/components/chat/ChatViewBubbleCore/cards/reply/ReplyCard.tsx
fixed the UI of the chat reply
Closes #1407 
- Fixed the text for the address on chat reply bubble
Twitter Preview is still left, it is under discussion on how to render the preview.
=> fix: fixed the theme for chat reply feature

packages/restapi/yarn.lock, packages/uiweb/src/lib/components/chat/ChatPreview/ChatPreview.tsx, packages/uiweb/src/lib/components/chat/ChatProfile/ChatProfile.tsx, packages/uiweb/src/lib/components/chat/CreateGroup/AddCriteria.tsx, packages/uiweb/src/lib/components/chat/UserProfile/UserProfile.tsx, packages/uiweb/src/lib/components/chat/helpers/tokenHelpers/chain.ts, packages/uiweb/src/lib/components/supportChat/AddressInfo.tsx, packages/uiweb/src/lib/config/constants.ts, packages/uiweb/src/lib/context/chatContext.ts, packages/uiweb/src/lib/dataProviders/ChatDataProvider.tsx, packages/uiweb/src/lib/dataProviders/Web3OnboardDataProvider.tsx, packages/uiweb/src/lib/helpers/address.ts, packages/uiweb/src/lib/helpers/udResolver.ts, packages/uiweb/src/lib/hooks/useAccount.ts, packages/uiweb/yarn.lock, yarn.lock
* fix: fixed font sizes and dark theme (#1376)
* fix: fixed font sizes and dark theme
* fix: fixed line height
* Add erc1155 to token gating group conditions (#1382)
* feat: add erc1155 to token gating group conditions
* fix: add tokenId to fetchContractInfo function
* lock file updated
---------
* Replaced useResolveWeb3Name hook with resolveWeb3Name helper function (#1390)
* fix: added common resolveweb3 for domain name
* fix: fixed review comments
* Notification Ui change (#1396)
* feat: new notification ui
* fix: fixed review comments
* lock file changed
* fix: fixed color and cta hover
* fix: fixed the review comments
* fix: fixed link icon
---------
* Push Chat Reply Feature (#1399)
* Functioning reply in ChatPreviewList, ChatList and Input
* Reply cancel and replying to in …
=> Updating alpha with main

packages/uiweb/src/lib/components/chat/ChatViewBubbleCore/CardRenderer.tsx, packages/uiweb/src/lib/components/chat/MessageInput/MessageInput.tsx
- Pass `messageType` as "MediaEmbed" for GIF media in `MessageInput`.
- Update `CardRenderer` to display GIF cards for both `messageType` values: "GIF" and "MediaEmbed".
=> SDK-1416: Update and Handle messageType for GIFs as MediaEmbed
